plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
url: "https://github.com/Raminkord92/Raminkord92.github.io"  # Your GitHub Pages URL
baseurl: ""  # Leave empty for user/organization pages